### ISSUE TITLE
mapa oucfl

### ISSUE THREAD

**Issue by yubathom** [SPURB/relatorios#10]
a partir da endpoint
https://servicos.spurbanismo.sp.gov.br/geo/api/mapas/1

criar mapa da oucfl. Esta página deverá ser criada em `/pages/oucfl/mapa`

protótipo
https://www.figma.com/file/jugasp0Tko3UBcxyk6ZDF6/spurb-servicos.spurbanismo.sp.gov.br-cepac?node-id=174%3A624

- [x] Renderizar mapa a partir do serviço de dados geográficos
- [x] Criar método e botão de exportação de arquivos `.geojson` na página do mapa
- [x] Criar método e botão de exportação de arquivos `.geojson` na páginas páginas `/cepac/:operação-urbana/:id`
- [x] Criar método e botão de exportação de arquivo de imagem do mapa (`.pdf`, `.png`, ou `.jpg`) na página do mapa

**Comment by m-dantas** [comment]
@yubathom deveria fechar está issue?

**Comment by yubathom** [comment]
Sim, pode fechar. Nos próximos inclua no comentário do commit `resolve #00` ou cite  (`relacionado a #00`) pra ficar traqueado
